adb devices 2>&1 | grep -E device$
if [ $? -ne 0  ] ; then echo "Missmatching device"; exit 1; fi

adb shell pm uninstall --user 0 com.wuba
adb shell pm uninstall --user 0 com.android.stk
adb shell pm uninstall --user 0 com.baidu.searchbox
adb shell pm uninstall --user 0 com.ximalaya.ting.android
adb shell pm uninstall --user 0 com.baidu.BaiduMap
adb shell pm uninstall --user 0 com.Qunar
adb shell pm uninstall --user 0 com.achievo.vipshop
adb shell pm uninstall --user 0 cn.wps.moffice_eng
adb shell pm uninstall --user 0 com.android.hwmirror
adb shell pm uninstall --user 0 com.eg.android.AlipayGphone
adb shell pm uninstall --user 0 com.taobao.taobao
adb shell pm uninstall --user 0 com.sina.weibo
adb shell pm uninstall --user 0 com.sohu.newsclient
adb shell pm uninstall --user 0 com.vmall.client
adb shell pm uninstall --user 0 com.jingdong.app.mall
adb shell pm uninstall --user 0 com.ss.android.article.news
adb shell pm uninstall --user 0 com.huawei.educenter
adb shell pm uninstall --user 0 com.tencent.mtt
adb shell pm uninstall --user 0 com.huawei.gamebox
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.huawei.videoeditor
adb shell pm uninstall --user 0 com.huawei.wallet
adb shell pm uninstall --user 0 com.android.mediacenter
adb shell pm uninstall --user 0 com.huawei.android.tips
adb shell pm uninstall --user 0 com.huawei.hicard
adb shell pm uninstall --user 0 com.android.providers.media
adb shell pm uninstall --user 0 com.sankuai.meituan
adb shell pm uninstall --user 0 com.huawei.search
adb shell pm uninstall --user 0 com.android.htmlviewer
adb shell pm uninstall --user 0 com.dianping.v1
adb shell pm uninstall --user 0 com.huawei.fastapp
adb shell pm uninstall --user 0 com.huawei.gameassistant
adb shell pm uninstall --user 0 com.huawei.hwvplayer.youku
adb shell pm uninstall --user 0 com.huawei.smarthome
adb shell pm uninstall --user 0 com.huawei.fans
adb shell pm uninstall --user 0 com.huawei.lives
adb shell pm uninstall --user 0 com.android.dreams.basic
adb shell pm uninstall --user 0 com.huawei.hilink.framework
adb shell pm uninstall --user 0 com.huawei.welinknow
adb shell pm uninstall --user 0 com.example.android.notepad
adb shell pm uninstall --user 0 com.huawei.hwireader
adb shell pm uninstall --user 0 com.android.email
adb shell pm uninstall --user 0 com.ss.android.ugc.aweme
adb shell pm uninstall --user 0 com.smile.gifmaker
adb shell pm uninstall --user 0 com.android.huawei.HiMediaEngine
adb shell pm uninstall --user 0 com.huawei.hifolder
adb shell pm uninstall --user 0 com.huawei.health
adb shell pm uninstall --user 0 com.huawei.vdrive
adb shell pm uninstall --user 0 com.hicloud.android.clone
adb shell pm uninstall --user 0 com.huawei.hiskytone
adb shell pm uninstall --user 0 com.android.browser
adb shell pm uninstall --user 0 com.huawei.mycenter
adb shell pm uninstall --user 0 com.huawei.KoBackup
adb shell pm uninstall --user 0 com.huawei.intelligent
adb shell pm uninstall --user 0 com.huawei.contentsensor
adb shell pm uninstall --user 0 com.android.wallpapercropper
adb shell pm uninstall --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall --user 0 com.huawei.android.karaoke
adb shell pm uninstall --user 0 com.huawei.bd
adb shell pm uninstall --user 0 com.huawei.ca
adb shell pm uninstall --user 0 com.huawei.hidisk
adb shell pm uninstall --user 0 com.huawei.hiview
adb shell pm uninstall --user 0 com.huawei.synergy
adb shell pm uninstall --user 0 com.huawei.hiviewtunnel
adb shell pm uninstall --user 0 com.huawei.pcassistant
adb shell pm uninstall --user 0 com.huawei.android.pushagent
adb shell pm uninstall --user 0 com.android.wallpaperbackup
adb shell pm uninstall --user 0 com.android.providers.userdictionary
adb shell pm uninstall --user 0 com.huawei.suggestion
adb shell pm uninstall --user 0 com.huawei.recsys
adb shell pm uninstall --user 0 com.iflytek.speechsuite
adb shell pm uninstall --user 0 com.huawei.hiai
adb shell pm uninstall --user 0 com.huawei.tips
adb shell pm uninstall --user 0 com.huawei.android.internal.app
adb shell pm uninstall --user 0 com.huawei.contactscamcard
adb shell pm uninstall --user 0 com.android.dreams.phototable
adb shell pm uninstall --user 0 com.huawei.hitouch
adb shell pm uninstall --user 0 com.huawei.android.projectmenu
adb shell pm uninstall --user 0 com.huawei.suggestion
adb shell pm uninstall --user 0 com.huawei.scanner
adb shell pm uninstall --user 0 com.huawei.hiaction
adb shell pm uninstall --user 0 com.baidu.input_huawei
adb shell pm uninstall --user 0 com.huawei.pengine
adb shell pm uninstall --user 0 com.huawei.mmitest
adb shell pm uninstall --user 0 com.huawei.hicloud
adb shell pm uninstall --user 0 com.huawei.vassistant
adb shell pm uninstall --user 0 com.android.simappdialog
adb shell pm uninstall --user 0 com.huawei.android.UEInfoCheck
adb shell pm uninstall --user 0 com.huawei.himovie
adb shell pm uninstall --user 0 com.huawei.hwdetectrepair
adb shell pm uninstall --user 0 com.huawei.phoneservice

adb install ./com.google.android.inputmethod.latin*apkmirror.com.apk
adb install ./via-release-cn.apk
